# Generated by Django 5.0.3 on 2024-03-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FR', 'мебель'), ('TECH', 'техника'), ('DISH', 'посуда')], default='FR', max_length=300, verbose_name='Категории'),
        ),
    ]
