# Generated by Django 5.0.3 on 2024-03-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_order_order_id_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата покупки'),
        ),
    ]
