# Generated by Django 5.0.3 on 2024-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата просмотра'),
        ),
    ]
