# Generated by Django 5.0.3 on 2024-04-12 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_watch_date_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeModel',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItemModel',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShoppingCartModel',
        ),
        migrations.RenameModel(
            old_name='Watch',
            new_name='WatchModel',
        ),
    ]
